//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RulesLib.VehicleDriverAssignmentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VehicleDriverAssignmentService.IVehDrvAssignmentService")]
    public interface IVehDrvAssignmentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehDrvAssignmentService/SetVehDrvAssignments", ReplyAction="http://tempuri.org/IVehDrvAssignmentService/SetVehDrvAssignmentsResponse")]
        CorPolicy.clsPolicyPPA SetVehDrvAssignments(CorPolicy.clsPolicyPPA pol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehDrvAssignmentService/SetVehDrvAssignments", ReplyAction="http://tempuri.org/IVehDrvAssignmentService/SetVehDrvAssignmentsResponse")]
        System.Threading.Tasks.Task<CorPolicy.clsPolicyPPA> SetVehDrvAssignmentsAsync(CorPolicy.clsPolicyPPA pol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehDrvAssignmentService/SetVehDrvAssignmentsSpecify", ReplyAction="http://tempuri.org/IVehDrvAssignmentService/SetVehDrvAssignmentsSpecifyResponse")]
        CorPolicy.clsPolicyPPA SetVehDrvAssignmentsSpecify(CorPolicy.clsPolicyPPA pol, string assignmentType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehDrvAssignmentService/SetVehDrvAssignmentsSpecify", ReplyAction="http://tempuri.org/IVehDrvAssignmentService/SetVehDrvAssignmentsSpecifyResponse")]
        System.Threading.Tasks.Task<CorPolicy.clsPolicyPPA> SetVehDrvAssignmentsSpecifyAsync(CorPolicy.clsPolicyPPA pol, string assignmentType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVehDrvAssignmentServiceChannel : RulesLib.VehicleDriverAssignmentService.IVehDrvAssignmentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehDrvAssignmentServiceClient : System.ServiceModel.ClientBase<RulesLib.VehicleDriverAssignmentService.IVehDrvAssignmentService>, RulesLib.VehicleDriverAssignmentService.IVehDrvAssignmentService {
        
        public VehDrvAssignmentServiceClient() {
        }
        
        public VehDrvAssignmentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehDrvAssignmentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehDrvAssignmentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehDrvAssignmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CorPolicy.clsPolicyPPA SetVehDrvAssignments(CorPolicy.clsPolicyPPA pol) {
            return base.Channel.SetVehDrvAssignments(pol);
        }
        
        public System.Threading.Tasks.Task<CorPolicy.clsPolicyPPA> SetVehDrvAssignmentsAsync(CorPolicy.clsPolicyPPA pol) {
            return base.Channel.SetVehDrvAssignmentsAsync(pol);
        }
        
        public CorPolicy.clsPolicyPPA SetVehDrvAssignmentsSpecify(CorPolicy.clsPolicyPPA pol, string assignmentType) {
            return base.Channel.SetVehDrvAssignmentsSpecify(pol, assignmentType);
        }
        
        public System.Threading.Tasks.Task<CorPolicy.clsPolicyPPA> SetVehDrvAssignmentsSpecifyAsync(CorPolicy.clsPolicyPPA pol, string assignmentType) {
            return base.Channel.SetVehDrvAssignmentsSpecifyAsync(pol, assignmentType);
        }
    }
}
