//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RulesLib.VINService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VINService.IVinService")]
    public interface IVinService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVinService/BridgeVINData", ReplyAction="http://tempuri.org/IVinService/BridgeVINDataResponse")]
        System.Data.DataSet BridgeVINData(string vin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVinService/BridgeVINData", ReplyAction="http://tempuri.org/IVinService/BridgeVINDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> BridgeVINDataAsync(string vin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVinService/VerifyCheckDigit", ReplyAction="http://tempuri.org/IVinService/VerifyCheckDigitResponse")]
        string VerifyCheckDigit(string vin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVinService/VerifyCheckDigit", ReplyAction="http://tempuri.org/IVinService/VerifyCheckDigitResponse")]
        System.Threading.Tasks.Task<string> VerifyCheckDigitAsync(string vin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVinServiceChannel : RulesLib.VINService.IVinService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VinServiceClient : System.ServiceModel.ClientBase<RulesLib.VINService.IVinService>, RulesLib.VINService.IVinService {
        
        public VinServiceClient() {
        }
        
        public VinServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VinServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VinServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VinServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet BridgeVINData(string vin) {
            return base.Channel.BridgeVINData(vin);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BridgeVINDataAsync(string vin) {
            return base.Channel.BridgeVINDataAsync(vin);
        }
        
        public string VerifyCheckDigit(string vin) {
            return base.Channel.VerifyCheckDigit(vin);
        }
        
        public System.Threading.Tasks.Task<string> VerifyCheckDigitAsync(string vin) {
            return base.Channel.VerifyCheckDigitAsync(vin);
        }
    }
}
