'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ErrorLoggingService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="com.insurcloud", ConfigurationName:="ErrorLoggingService.ErrorLoggingServiceSoap")>  _
    Public Interface ErrorLoggingServiceSoap
        
        'CODEGEN: Generating message contract since element name SourceSystem from namespace com.insurcloud is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/TestLoggingWithReference", ReplyAction:="*")>  _
        Function TestLoggingWithReference(ByVal request As ErrorLoggingService.TestLoggingWithReferenceRequest) As ErrorLoggingService.TestLoggingWithReferenceResponse
        
        'CODEGEN: Generating message contract since element name SourceSystem from namespace com.insurcloud is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/TestLogging", ReplyAction:="*")>  _
        Function TestLogging(ByVal request As ErrorLoggingService.TestLoggingRequest) As ErrorLoggingService.TestLoggingResponse
        
        'CODEGEN: Generating message contract since element name sXML from namespace com.insurcloud is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/LogErrorXML", ReplyAction:="*")>  _
        Function LogErrorXML(ByVal request As ErrorLoggingService.LogErrorXMLRequest) As ErrorLoggingService.LogErrorXMLResponse
        
        'CODEGEN: Generating message contract since element name sXML from namespace com.insurcloud is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/LogErrorXMLWithReference", ReplyAction:="*")>  _
        Function LogErrorXMLWithReference(ByVal request As ErrorLoggingService.LogErrorXMLWithReferenceRequest) As ErrorLoggingService.LogErrorXMLWithReferenceResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TestLoggingWithReferenceRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TestLoggingWithReference", [Namespace]:="com.insurcloud", Order:=0)>  _
        Public Body As ErrorLoggingService.TestLoggingWithReferenceRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ErrorLoggingService.TestLoggingWithReferenceRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class TestLoggingWithReferenceRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SourceSystem As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public ReferenceType As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public ReferenceID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public SystemTS As Date
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SourceSystem As String, ByVal ReferenceType As String, ByVal ReferenceID As String, ByVal SystemTS As Date)
            MyBase.New
            Me.SourceSystem = SourceSystem
            Me.ReferenceType = ReferenceType
            Me.ReferenceID = ReferenceID
            Me.SystemTS = SystemTS
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TestLoggingWithReferenceResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TestLoggingWithReferenceResponse", [Namespace]:="com.insurcloud", Order:=0)>  _
        Public Body As ErrorLoggingService.TestLoggingWithReferenceResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ErrorLoggingService.TestLoggingWithReferenceResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class TestLoggingWithReferenceResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public TestLoggingWithReferenceResult As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TestLoggingWithReferenceResult As Integer)
            MyBase.New
            Me.TestLoggingWithReferenceResult = TestLoggingWithReferenceResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TestLoggingRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TestLogging", [Namespace]:="com.insurcloud", Order:=0)>  _
        Public Body As ErrorLoggingService.TestLoggingRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ErrorLoggingService.TestLoggingRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class TestLoggingRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SourceSystem As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public SystemTS As Date
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SourceSystem As String, ByVal SystemTS As Date)
            MyBase.New
            Me.SourceSystem = SourceSystem
            Me.SystemTS = SystemTS
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TestLoggingResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TestLoggingResponse", [Namespace]:="com.insurcloud", Order:=0)>  _
        Public Body As ErrorLoggingService.TestLoggingResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ErrorLoggingService.TestLoggingResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class TestLoggingResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public TestLoggingResult As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TestLoggingResult As Integer)
            MyBase.New
            Me.TestLoggingResult = TestLoggingResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LogErrorXMLRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LogErrorXML", [Namespace]:="com.insurcloud", Order:=0)>  _
        Public Body As ErrorLoggingService.LogErrorXMLRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ErrorLoggingService.LogErrorXMLRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class LogErrorXMLRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public sXML As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public SourceSystem As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public SystemTS As Date
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal sXML As System.Xml.Linq.XElement, ByVal SourceSystem As String, ByVal SystemTS As Date)
            MyBase.New
            Me.sXML = sXML
            Me.SourceSystem = SourceSystem
            Me.SystemTS = SystemTS
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LogErrorXMLResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LogErrorXMLResponse", [Namespace]:="com.insurcloud", Order:=0)>  _
        Public Body As ErrorLoggingService.LogErrorXMLResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ErrorLoggingService.LogErrorXMLResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class LogErrorXMLResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public LogErrorXMLResult As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LogErrorXMLResult As Integer)
            MyBase.New
            Me.LogErrorXMLResult = LogErrorXMLResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LogErrorXMLWithReferenceRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LogErrorXMLWithReference", [Namespace]:="com.insurcloud", Order:=0)>  _
        Public Body As ErrorLoggingService.LogErrorXMLWithReferenceRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ErrorLoggingService.LogErrorXMLWithReferenceRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class LogErrorXMLWithReferenceRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public sXML As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public SourceSystem As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public ReferenceType As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public ReferenceID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public SystemTS As Date
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal sXML As System.Xml.Linq.XElement, ByVal SourceSystem As String, ByVal ReferenceType As String, ByVal ReferenceID As String, ByVal SystemTS As Date)
            MyBase.New
            Me.sXML = sXML
            Me.SourceSystem = SourceSystem
            Me.ReferenceType = ReferenceType
            Me.ReferenceID = ReferenceID
            Me.SystemTS = SystemTS
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LogErrorXMLWithReferenceResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LogErrorXMLWithReferenceResponse", [Namespace]:="com.insurcloud", Order:=0)>  _
        Public Body As ErrorLoggingService.LogErrorXMLWithReferenceResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ErrorLoggingService.LogErrorXMLWithReferenceResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class LogErrorXMLWithReferenceResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public LogErrorXMLWithReferenceResult As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LogErrorXMLWithReferenceResult As Integer)
            MyBase.New
            Me.LogErrorXMLWithReferenceResult = LogErrorXMLWithReferenceResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ErrorLoggingServiceSoapChannel
        Inherits ErrorLoggingService.ErrorLoggingServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ErrorLoggingServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of ErrorLoggingService.ErrorLoggingServiceSoap)
        Implements ErrorLoggingService.ErrorLoggingServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ErrorLoggingService_ErrorLoggingServiceSoap_TestLoggingWithReference(ByVal request As ErrorLoggingService.TestLoggingWithReferenceRequest) As ErrorLoggingService.TestLoggingWithReferenceResponse Implements ErrorLoggingService.ErrorLoggingServiceSoap.TestLoggingWithReference
            Return MyBase.Channel.TestLoggingWithReference(request)
        End Function
        
        Public Function TestLoggingWithReference(ByVal SourceSystem As String, ByVal ReferenceType As String, ByVal ReferenceID As String, ByVal SystemTS As Date) As Integer
            Dim inValue As ErrorLoggingService.TestLoggingWithReferenceRequest = New ErrorLoggingService.TestLoggingWithReferenceRequest()
            inValue.Body = New ErrorLoggingService.TestLoggingWithReferenceRequestBody()
            inValue.Body.SourceSystem = SourceSystem
            inValue.Body.ReferenceType = ReferenceType
            inValue.Body.ReferenceID = ReferenceID
            inValue.Body.SystemTS = SystemTS
            Dim retVal As ErrorLoggingService.TestLoggingWithReferenceResponse = CType(Me,ErrorLoggingService.ErrorLoggingServiceSoap).TestLoggingWithReference(inValue)
            Return retVal.Body.TestLoggingWithReferenceResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ErrorLoggingService_ErrorLoggingServiceSoap_TestLogging(ByVal request As ErrorLoggingService.TestLoggingRequest) As ErrorLoggingService.TestLoggingResponse Implements ErrorLoggingService.ErrorLoggingServiceSoap.TestLogging
            Return MyBase.Channel.TestLogging(request)
        End Function
        
        Public Function TestLogging(ByVal SourceSystem As String, ByVal SystemTS As Date) As Integer
            Dim inValue As ErrorLoggingService.TestLoggingRequest = New ErrorLoggingService.TestLoggingRequest()
            inValue.Body = New ErrorLoggingService.TestLoggingRequestBody()
            inValue.Body.SourceSystem = SourceSystem
            inValue.Body.SystemTS = SystemTS
            Dim retVal As ErrorLoggingService.TestLoggingResponse = CType(Me,ErrorLoggingService.ErrorLoggingServiceSoap).TestLogging(inValue)
            Return retVal.Body.TestLoggingResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ErrorLoggingService_ErrorLoggingServiceSoap_LogErrorXML(ByVal request As ErrorLoggingService.LogErrorXMLRequest) As ErrorLoggingService.LogErrorXMLResponse Implements ErrorLoggingService.ErrorLoggingServiceSoap.LogErrorXML
            Return MyBase.Channel.LogErrorXML(request)
        End Function
        
        Public Function LogErrorXML(ByVal sXML As System.Xml.Linq.XElement, ByVal SourceSystem As String, ByVal SystemTS As Date) As Integer
            Dim inValue As ErrorLoggingService.LogErrorXMLRequest = New ErrorLoggingService.LogErrorXMLRequest()
            inValue.Body = New ErrorLoggingService.LogErrorXMLRequestBody()
            inValue.Body.sXML = sXML
            inValue.Body.SourceSystem = SourceSystem
            inValue.Body.SystemTS = SystemTS
            Dim retVal As ErrorLoggingService.LogErrorXMLResponse = CType(Me,ErrorLoggingService.ErrorLoggingServiceSoap).LogErrorXML(inValue)
            Return retVal.Body.LogErrorXMLResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ErrorLoggingService_ErrorLoggingServiceSoap_LogErrorXMLWithReference(ByVal request As ErrorLoggingService.LogErrorXMLWithReferenceRequest) As ErrorLoggingService.LogErrorXMLWithReferenceResponse Implements ErrorLoggingService.ErrorLoggingServiceSoap.LogErrorXMLWithReference
            Return MyBase.Channel.LogErrorXMLWithReference(request)
        End Function
        
        Public Function LogErrorXMLWithReference(ByVal sXML As System.Xml.Linq.XElement, ByVal SourceSystem As String, ByVal ReferenceType As String, ByVal ReferenceID As String, ByVal SystemTS As Date) As Integer
            Dim inValue As ErrorLoggingService.LogErrorXMLWithReferenceRequest = New ErrorLoggingService.LogErrorXMLWithReferenceRequest()
            inValue.Body = New ErrorLoggingService.LogErrorXMLWithReferenceRequestBody()
            inValue.Body.sXML = sXML
            inValue.Body.SourceSystem = SourceSystem
            inValue.Body.ReferenceType = ReferenceType
            inValue.Body.ReferenceID = ReferenceID
            inValue.Body.SystemTS = SystemTS
            Dim retVal As ErrorLoggingService.LogErrorXMLWithReferenceResponse = CType(Me,ErrorLoggingService.ErrorLoggingServiceSoap).LogErrorXMLWithReference(inValue)
            Return retVal.Body.LogErrorXMLWithReferenceResult
        End Function
    End Class
End Namespace
