'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace VinService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="VinService.IVinService")>  _
    Public Interface IVinService
        
        'CODEGEN: Parameter 'BridgeVINDataResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IVinService/BridgeVINData", ReplyAction:="http://tempuri.org/IVinService/BridgeVINDataResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function BridgeVINData(ByVal request As VinService.BridgeVINDataRequest) As VinService.BridgeVINDataResponse
        
        'CODEGEN: Parameter 'VerifyCheckDigitResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IVinService/VerifyCheckDigit", ReplyAction:="http://tempuri.org/IVinService/VerifyCheckDigitResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function VerifyCheckDigit(ByVal request As VinService.VerifyCheckDigitRequest) As VinService.VerifyCheckDigitResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="BridgeVINData", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class BridgeVINDataRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public vin As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal vin As String)
            MyBase.New
            Me.vin = vin
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="BridgeVINDataResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class BridgeVINDataResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public BridgeVINDataResult As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal BridgeVINDataResult As System.Data.DataSet)
            MyBase.New
            Me.BridgeVINDataResult = BridgeVINDataResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="VerifyCheckDigit", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class VerifyCheckDigitRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public vin As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal vin As String)
            MyBase.New
            Me.vin = vin
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="VerifyCheckDigitResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class VerifyCheckDigitResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public VerifyCheckDigitResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal VerifyCheckDigitResult As String)
            MyBase.New
            Me.VerifyCheckDigitResult = VerifyCheckDigitResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IVinServiceChannel
        Inherits VinService.IVinService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class VinServiceClient
        Inherits System.ServiceModel.ClientBase(Of VinService.IVinService)
        Implements VinService.IVinService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VinService_IVinService_BridgeVINData(ByVal request As VinService.BridgeVINDataRequest) As VinService.BridgeVINDataResponse Implements VinService.IVinService.BridgeVINData
            Return MyBase.Channel.BridgeVINData(request)
        End Function
        
        Public Function BridgeVINData(ByVal vin As String) As System.Data.DataSet
            Dim inValue As VinService.BridgeVINDataRequest = New VinService.BridgeVINDataRequest()
            inValue.vin = vin
            Dim retVal As VinService.BridgeVINDataResponse = CType(Me,VinService.IVinService).BridgeVINData(inValue)
            Return retVal.BridgeVINDataResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VinService_IVinService_VerifyCheckDigit(ByVal request As VinService.VerifyCheckDigitRequest) As VinService.VerifyCheckDigitResponse Implements VinService.IVinService.VerifyCheckDigit
            Return MyBase.Channel.VerifyCheckDigit(request)
        End Function
        
        Public Function VerifyCheckDigit(ByVal vin As String) As String
            Dim inValue As VinService.VerifyCheckDigitRequest = New VinService.VerifyCheckDigitRequest()
            inValue.vin = vin
            Dim retVal As VinService.VerifyCheckDigitResponse = CType(Me,VinService.IVinService).VerifyCheckDigit(inValue)
            Return retVal.VerifyCheckDigitResult
        End Function
    End Class
End Namespace
