'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace MarketingCRMService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="com.insurcloud", ConfigurationName:="MarketingCRMService.InsurCloudAMSServiceSoap")>  _
    Public Interface InsurCloudAMSServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/InsertAgency", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function InsertAgency(ByRef oAgency As MarketingCRMService.Agency, ByVal isPASAgency As Boolean) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/InsertLocation", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function InsertLocation(ByRef oLoc As MarketingCRMService.Location, ByRef oAgent As MarketingCRMService.Agency, ByVal isPASAgency As Boolean) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/InsertBank", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function InsertBank(ByVal oObject As Object, ByRef oBank As MarketingCRMService.Bank) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/GetActivePrograms", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetActivePrograms(ByVal productCode As Integer, ByVal stateCode As String) As MarketingCRMService.Program()
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/InsertProgram", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function InsertProgram(ByRef oProg As MarketingCRMService.LocationProgram, ByVal ProgramCode As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/LoadAgency", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LoadAgency(ByVal AgentCode As String, ByVal LoadAll As Boolean, ByVal ProgramCode As String) As MarketingCRMService.Agency
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/GetOptions", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetOptions(ByVal AgentCode As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/isInSameGroup", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function isInSameGroup(ByVal AgentCode1 As String, ByVal AgentCode2 As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/IsCommissionStatementPaperless", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function IsCommissionStatementPaperless(ByVal agencyId As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/CommissionStatementPaperlessUpdate", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CommissionStatementPaperlessUpdate(ByVal agencyId As String, ByVal isPaperless As Boolean) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/CommissionLoginIsAllowed", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CommissionLoginIsAllowed(ByVal LocationCode As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/CommissionLoginCreate", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CommissionLoginCreate(ByVal LocationCode As String, ByVal Password As String, ByVal CreatedBy As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/CommissionLoginUpdate", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CommissionLoginUpdate(ByVal LocationCode As String, ByVal NewPassword As String, ByVal UpdatedPasswordBy As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/CommissionLoginUpdateForAgent", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CommissionLoginUpdateForAgent(ByVal LocationCode As String, ByVal OldPassword As String, ByVal NewPassword As String, ByVal UpdatedPasswordBy As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/CommissionLoginIsRegistered", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CommissionLoginIsRegistered(ByVal LocationCode As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/CommissionLoginIsRegisteredInfoValid", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CommissionLoginIsRegisteredInfoValid(ByVal LocationCode As String, ByVal TaxIDorSSN As String, ByVal ZipCode As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/CommissionLogin", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CommissionLogin(ByVal LocationCode As String, ByVal Password As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/CommissionLoginEmailUpdate", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CommissionLoginEmailUpdate(ByVal LocationCode As String, ByVal NewEmail As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/ESignatureStatusUpdate", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ESignatureStatusUpdate(ByVal agencyId As String, ByVal isESignature As Boolean) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/ResetAgentPassword", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ResetAgentPassword(ByVal agent As MarketingCRMService.BaseAgent) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/UpdateAgentPassword", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UpdateAgentPassword(ByVal agent As MarketingCRMService.BaseAgent) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/IsAgentRequiredToUpdatePassword", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function IsAgentRequiredToUpdatePassword(ByVal agent As MarketingCRMService.BaseAgent) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="com.insurcloud/LoadMarketingComboBox", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LoadMarketingComboBox(ByVal sProgramType As String, ByVal sCategory As String, ByVal sSubCategory As String, ByVal sAppliesToCode As String, ByVal dtRateDate As Date) As System.Data.DataSet
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class Agency
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private agencyIDField As Decimal
        
        Private nameField As String
        
        Private dBAField As String
        
        Private busTypeCodeField As String
        
        Private uRLField As String
        
        Private agentCodeField As String
        
        Private issue1099Field As Boolean
        
        Private emailRptGrpField As Boolean
        
        Private nameLicensedField As String
        
        Private licenseNumField As String
        
        Private dateField As Date
        
        Private enteredByField As String
        
        Private locationsField() As Location
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property AgencyID() As Decimal
            Get
                Return Me.agencyIDField
            End Get
            Set
                Me.agencyIDField = value
                Me.RaisePropertyChanged("AgencyID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
                Me.RaisePropertyChanged("Name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property DBA() As String
            Get
                Return Me.dBAField
            End Get
            Set
                Me.dBAField = value
                Me.RaisePropertyChanged("DBA")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property BusTypeCode() As String
            Get
                Return Me.busTypeCodeField
            End Get
            Set
                Me.busTypeCodeField = value
                Me.RaisePropertyChanged("BusTypeCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property URL() As String
            Get
                Return Me.uRLField
            End Get
            Set
                Me.uRLField = value
                Me.RaisePropertyChanged("URL")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property AgentCode() As String
            Get
                Return Me.agentCodeField
            End Get
            Set
                Me.agentCodeField = value
                Me.RaisePropertyChanged("AgentCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property issue1099() As Boolean
            Get
                Return Me.issue1099Field
            End Get
            Set
                Me.issue1099Field = value
                Me.RaisePropertyChanged("issue1099")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property EmailRptGrp() As Boolean
            Get
                Return Me.emailRptGrpField
            End Get
            Set
                Me.emailRptGrpField = value
                Me.RaisePropertyChanged("EmailRptGrp")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property NameLicensed() As String
            Get
                Return Me.nameLicensedField
            End Get
            Set
                Me.nameLicensedField = value
                Me.RaisePropertyChanged("NameLicensed")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property LicenseNum() As String
            Get
                Return Me.licenseNumField
            End Get
            Set
                Me.licenseNumField = value
                Me.RaisePropertyChanged("LicenseNum")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property [Date]() As Date
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
                Me.RaisePropertyChanged("Date")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property EnteredBy() As String
            Get
                Return Me.enteredByField
            End Get
            Set
                Me.enteredByField = value
                Me.RaisePropertyChanged("EnteredBy")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=12)>  _
        Public Property Locations() As Location()
            Get
                Return Me.locationsField
            End Get
            Set
                Me.locationsField = value
                Me.RaisePropertyChanged("Locations")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class Location
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private locationIDField As Decimal
        
        Private locationNameField As String
        
        Private address1Field As String
        
        Private address2Field As String
        
        Private cityField As String
        
        Private stateAbbrField As String
        
        Private zipCodeField As String
        
        Private geoCoordLatField As String
        
        Private geoCoordLongField As String
        
        Private phone1Field As String
        
        Private phone2Field As String
        
        Private faxField As String
        
        Private emailAddrField As String
        
        Private agencyIDField As System.Nullable(Of Decimal)
        
        Private repIDField As System.Nullable(Of Decimal)
        
        Private isActiveField As Boolean
        
        Private isShipAddrField As Boolean
        
        Private isStatementAddrField As Boolean
        
        Private isESignatureField As Boolean
        
        Private emailRptAgtField As Boolean
        
        Private epayField As Boolean
        
        Private edocField As Boolean
        
        Private defaultAgencyCodeField As String
        
        Private statusCodeField As String
        
        Private taxIDField As String
        
        Private sSNField As String
        
        Private transferToAgentField As String
        
        Private comparativeRaterField As String
        
        Private dateField As Date
        
        Private enteredByField As String
        
        Private altAddressesField() As AltAddress
        
        Private locationBanksField() As LocationBank
        
        Private locationIVANsField() As LocationIVAN
        
        Private locationProgramsField() As LocationProgram
        
        Private repField As Rep
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property LocationID() As Decimal
            Get
                Return Me.locationIDField
            End Get
            Set
                Me.locationIDField = value
                Me.RaisePropertyChanged("LocationID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property LocationName() As String
            Get
                Return Me.locationNameField
            End Get
            Set
                Me.locationNameField = value
                Me.RaisePropertyChanged("LocationName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Address1() As String
            Get
                Return Me.address1Field
            End Get
            Set
                Me.address1Field = value
                Me.RaisePropertyChanged("Address1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Address2() As String
            Get
                Return Me.address2Field
            End Get
            Set
                Me.address2Field = value
                Me.RaisePropertyChanged("Address2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property City() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = value
                Me.RaisePropertyChanged("City")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property StateAbbr() As String
            Get
                Return Me.stateAbbrField
            End Get
            Set
                Me.stateAbbrField = value
                Me.RaisePropertyChanged("StateAbbr")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property ZipCode() As String
            Get
                Return Me.zipCodeField
            End Get
            Set
                Me.zipCodeField = value
                Me.RaisePropertyChanged("ZipCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property GeoCoordLat() As String
            Get
                Return Me.geoCoordLatField
            End Get
            Set
                Me.geoCoordLatField = value
                Me.RaisePropertyChanged("GeoCoordLat")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property GeoCoordLong() As String
            Get
                Return Me.geoCoordLongField
            End Get
            Set
                Me.geoCoordLongField = value
                Me.RaisePropertyChanged("GeoCoordLong")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property Phone1() As String
            Get
                Return Me.phone1Field
            End Get
            Set
                Me.phone1Field = value
                Me.RaisePropertyChanged("Phone1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property Phone2() As String
            Get
                Return Me.phone2Field
            End Get
            Set
                Me.phone2Field = value
                Me.RaisePropertyChanged("Phone2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property Fax() As String
            Get
                Return Me.faxField
            End Get
            Set
                Me.faxField = value
                Me.RaisePropertyChanged("Fax")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property EmailAddr() As String
            Get
                Return Me.emailAddrField
            End Get
            Set
                Me.emailAddrField = value
                Me.RaisePropertyChanged("EmailAddr")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=13)>  _
        Public Property AgencyID() As System.Nullable(Of Decimal)
            Get
                Return Me.agencyIDField
            End Get
            Set
                Me.agencyIDField = value
                Me.RaisePropertyChanged("AgencyID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=14)>  _
        Public Property RepID() As System.Nullable(Of Decimal)
            Get
                Return Me.repIDField
            End Get
            Set
                Me.repIDField = value
                Me.RaisePropertyChanged("RepID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=15)>  _
        Public Property isActive() As Boolean
            Get
                Return Me.isActiveField
            End Get
            Set
                Me.isActiveField = value
                Me.RaisePropertyChanged("isActive")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=16)>  _
        Public Property isShipAddr() As Boolean
            Get
                Return Me.isShipAddrField
            End Get
            Set
                Me.isShipAddrField = value
                Me.RaisePropertyChanged("isShipAddr")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=17)>  _
        Public Property isStatementAddr() As Boolean
            Get
                Return Me.isStatementAddrField
            End Get
            Set
                Me.isStatementAddrField = value
                Me.RaisePropertyChanged("isStatementAddr")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=18)>  _
        Public Property isESignature() As Boolean
            Get
                Return Me.isESignatureField
            End Get
            Set
                Me.isESignatureField = value
                Me.RaisePropertyChanged("isESignature")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=19)>  _
        Public Property EmailRptAgt() As Boolean
            Get
                Return Me.emailRptAgtField
            End Get
            Set
                Me.emailRptAgtField = value
                Me.RaisePropertyChanged("EmailRptAgt")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=20)>  _
        Public Property Epay() As Boolean
            Get
                Return Me.epayField
            End Get
            Set
                Me.epayField = value
                Me.RaisePropertyChanged("Epay")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=21)>  _
        Public Property Edoc() As Boolean
            Get
                Return Me.edocField
            End Get
            Set
                Me.edocField = value
                Me.RaisePropertyChanged("Edoc")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=22)>  _
        Public Property DefaultAgencyCode() As String
            Get
                Return Me.defaultAgencyCodeField
            End Get
            Set
                Me.defaultAgencyCodeField = value
                Me.RaisePropertyChanged("DefaultAgencyCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=23)>  _
        Public Property StatusCode() As String
            Get
                Return Me.statusCodeField
            End Get
            Set
                Me.statusCodeField = value
                Me.RaisePropertyChanged("StatusCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=24)>  _
        Public Property TaxID() As String
            Get
                Return Me.taxIDField
            End Get
            Set
                Me.taxIDField = value
                Me.RaisePropertyChanged("TaxID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=25)>  _
        Public Property SSN() As String
            Get
                Return Me.sSNField
            End Get
            Set
                Me.sSNField = value
                Me.RaisePropertyChanged("SSN")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=26)>  _
        Public Property TransferToAgent() As String
            Get
                Return Me.transferToAgentField
            End Get
            Set
                Me.transferToAgentField = value
                Me.RaisePropertyChanged("TransferToAgent")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=27)>  _
        Public Property ComparativeRater() As String
            Get
                Return Me.comparativeRaterField
            End Get
            Set
                Me.comparativeRaterField = value
                Me.RaisePropertyChanged("ComparativeRater")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=28)>  _
        Public Property [Date]() As Date
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
                Me.RaisePropertyChanged("Date")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=29)>  _
        Public Property EnteredBy() As String
            Get
                Return Me.enteredByField
            End Get
            Set
                Me.enteredByField = value
                Me.RaisePropertyChanged("EnteredBy")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=30)>  _
        Public Property AltAddresses() As AltAddress()
            Get
                Return Me.altAddressesField
            End Get
            Set
                Me.altAddressesField = value
                Me.RaisePropertyChanged("AltAddresses")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=31)>  _
        Public Property LocationBanks() As LocationBank()
            Get
                Return Me.locationBanksField
            End Get
            Set
                Me.locationBanksField = value
                Me.RaisePropertyChanged("LocationBanks")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=32)>  _
        Public Property LocationIVANs() As LocationIVAN()
            Get
                Return Me.locationIVANsField
            End Get
            Set
                Me.locationIVANsField = value
                Me.RaisePropertyChanged("LocationIVANs")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=33)>  _
        Public Property LocationPrograms() As LocationProgram()
            Get
                Return Me.locationProgramsField
            End Get
            Set
                Me.locationProgramsField = value
                Me.RaisePropertyChanged("LocationPrograms")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=34)>  _
        Public Property Rep() As Rep
            Get
                Return Me.repField
            End Get
            Set
                Me.repField = value
                Me.RaisePropertyChanged("Rep")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class AltAddress
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private addressIDField As Decimal
        
        Private locationIDField As Decimal
        
        Private addressTypeField As String
        
        Private address1Field As String
        
        Private address2Field As String
        
        Private cityField As String
        
        Private stateField As String
        
        Private zipField As String
        
        Private isActiveField As Boolean
        
        Private dateField As Date
        
        Private enteredByField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property AddressID() As Decimal
            Get
                Return Me.addressIDField
            End Get
            Set
                Me.addressIDField = value
                Me.RaisePropertyChanged("AddressID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property LocationID() As Decimal
            Get
                Return Me.locationIDField
            End Get
            Set
                Me.locationIDField = value
                Me.RaisePropertyChanged("LocationID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property AddressType() As String
            Get
                Return Me.addressTypeField
            End Get
            Set
                Me.addressTypeField = value
                Me.RaisePropertyChanged("AddressType")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Address1() As String
            Get
                Return Me.address1Field
            End Get
            Set
                Me.address1Field = value
                Me.RaisePropertyChanged("Address1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Address2() As String
            Get
                Return Me.address2Field
            End Get
            Set
                Me.address2Field = value
                Me.RaisePropertyChanged("Address2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property City() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = value
                Me.RaisePropertyChanged("City")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property State() As String
            Get
                Return Me.stateField
            End Get
            Set
                Me.stateField = value
                Me.RaisePropertyChanged("State")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property Zip() As String
            Get
                Return Me.zipField
            End Get
            Set
                Me.zipField = value
                Me.RaisePropertyChanged("Zip")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property isActive() As Boolean
            Get
                Return Me.isActiveField
            End Get
            Set
                Me.isActiveField = value
                Me.RaisePropertyChanged("isActive")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property [Date]() As Date
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
                Me.RaisePropertyChanged("Date")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property EnteredBy() As String
            Get
                Return Me.enteredByField
            End Get
            Set
                Me.enteredByField = value
                Me.RaisePropertyChanged("EnteredBy")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(Agent)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public MustInherit Class BaseAgent
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private emailAddressField As String
        
        Private passwordField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property EmailAddress() As String
            Get
                Return Me.emailAddressField
            End Get
            Set
                Me.emailAddressField = value
                Me.RaisePropertyChanged("EmailAddress")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("Password")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class Agent
        Inherits BaseAgent
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class Program
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private programIDField As Integer
        
        Private programCodeField As String
        
        Private productCodeField As Integer
        
        Private stateCodeField As String
        
        Private appliesToCodeField As Char
        
        Private programTypeField As String
        
        Private productField As String
        
        Private expDateField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ProgramID() As Integer
            Get
                Return Me.programIDField
            End Get
            Set
                Me.programIDField = value
                Me.RaisePropertyChanged("ProgramID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property ProgramCode() As String
            Get
                Return Me.programCodeField
            End Get
            Set
                Me.programCodeField = value
                Me.RaisePropertyChanged("ProgramCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ProductCode() As Integer
            Get
                Return Me.productCodeField
            End Get
            Set
                Me.productCodeField = value
                Me.RaisePropertyChanged("ProductCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property StateCode() As String
            Get
                Return Me.stateCodeField
            End Get
            Set
                Me.stateCodeField = value
                Me.RaisePropertyChanged("StateCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property AppliesToCode() As Char
            Get
                Return Me.appliesToCodeField
            End Get
            Set
                Me.appliesToCodeField = value
                Me.RaisePropertyChanged("AppliesToCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property ProgramType() As String
            Get
                Return Me.programTypeField
            End Get
            Set
                Me.programTypeField = value
                Me.RaisePropertyChanged("ProgramType")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property Product() As String
            Get
                Return Me.productField
            End Get
            Set
                Me.productField = value
                Me.RaisePropertyChanged("Product")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property ExpDate() As Date
            Get
                Return Me.expDateField
            End Get
            Set
                Me.expDateField = value
                Me.RaisePropertyChanged("ExpDate")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class Rep
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private repIDField As Decimal
        
        Private nameField As String
        
        Private phoneField As String
        
        Private phoneExtField As String
        
        Private emailField As String
        
        Private territoryNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property RepID() As Decimal
            Get
                Return Me.repIDField
            End Get
            Set
                Me.repIDField = value
                Me.RaisePropertyChanged("RepID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
                Me.RaisePropertyChanged("Name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Phone() As String
            Get
                Return Me.phoneField
            End Get
            Set
                Me.phoneField = value
                Me.RaisePropertyChanged("Phone")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property PhoneExt() As String
            Get
                Return Me.phoneExtField
            End Get
            Set
                Me.phoneExtField = value
                Me.RaisePropertyChanged("PhoneExt")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
                Me.RaisePropertyChanged("Email")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property TerritoryName() As String
            Get
                Return Me.territoryNameField
            End Get
            Set
                Me.territoryNameField = value
                Me.RaisePropertyChanged("TerritoryName")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class pgmProgram
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private programIdField As Decimal
        
        Private companyNameField As String
        
        Private companyCodeField As String
        
        Private productCodeField As String
        
        Private productIDField As Integer
        
        Private stateCodeField As String
        
        Private programCodeField As String
        
        Private systemCodeField As String
        
        Private nameField As String
        
        Private descriptionField As String
        
        Private displayField As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ProgramId() As Decimal
            Get
                Return Me.programIdField
            End Get
            Set
                Me.programIdField = value
                Me.RaisePropertyChanged("ProgramId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property CompanyName() As String
            Get
                Return Me.companyNameField
            End Get
            Set
                Me.companyNameField = value
                Me.RaisePropertyChanged("CompanyName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property CompanyCode() As String
            Get
                Return Me.companyCodeField
            End Get
            Set
                Me.companyCodeField = value
                Me.RaisePropertyChanged("CompanyCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property ProductCode() As String
            Get
                Return Me.productCodeField
            End Get
            Set
                Me.productCodeField = value
                Me.RaisePropertyChanged("ProductCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property ProductID() As Integer
            Get
                Return Me.productIDField
            End Get
            Set
                Me.productIDField = value
                Me.RaisePropertyChanged("ProductID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property StateCode() As String
            Get
                Return Me.stateCodeField
            End Get
            Set
                Me.stateCodeField = value
                Me.RaisePropertyChanged("StateCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property ProgramCode() As String
            Get
                Return Me.programCodeField
            End Get
            Set
                Me.programCodeField = value
                Me.RaisePropertyChanged("ProgramCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property SystemCode() As String
            Get
                Return Me.systemCodeField
            End Get
            Set
                Me.systemCodeField = value
                Me.RaisePropertyChanged("SystemCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
                Me.RaisePropertyChanged("Name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
                Me.RaisePropertyChanged("Description")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property Display() As Boolean
            Get
                Return Me.displayField
            End Get
            Set
                Me.displayField = value
                Me.RaisePropertyChanged("Display")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class LocationProgram
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private xIDField As Integer
        
        Private programIdField As Decimal
        
        Private locationIdField As Decimal
        
        Private systemCredentialField As String
        
        Private newBusPctField As System.Nullable(Of Decimal)
        
        Private renewBusPctField As System.Nullable(Of Decimal)
        
        Private rolloverPctField As System.Nullable(Of Decimal)
        
        Private payCommissionCodeField As System.Nullable(Of Char)
        
        Private effDateField As System.Nullable(Of Date)
        
        Private expDateField As System.Nullable(Of Date)
        
        Private dateField As Date
        
        Private enteredByField As String
        
        Private appliesToCodeField As String
        
        Private pgmProgramField As pgmProgram
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property xID() As Integer
            Get
                Return Me.xIDField
            End Get
            Set
                Me.xIDField = value
                Me.RaisePropertyChanged("xID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property ProgramId() As Decimal
            Get
                Return Me.programIdField
            End Get
            Set
                Me.programIdField = value
                Me.RaisePropertyChanged("ProgramId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property LocationId() As Decimal
            Get
                Return Me.locationIdField
            End Get
            Set
                Me.locationIdField = value
                Me.RaisePropertyChanged("LocationId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property SystemCredential() As String
            Get
                Return Me.systemCredentialField
            End Get
            Set
                Me.systemCredentialField = value
                Me.RaisePropertyChanged("SystemCredential")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
        Public Property NewBusPct() As System.Nullable(Of Decimal)
            Get
                Return Me.newBusPctField
            End Get
            Set
                Me.newBusPctField = value
                Me.RaisePropertyChanged("NewBusPct")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=5)>  _
        Public Property RenewBusPct() As System.Nullable(Of Decimal)
            Get
                Return Me.renewBusPctField
            End Get
            Set
                Me.renewBusPctField = value
                Me.RaisePropertyChanged("RenewBusPct")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=6)>  _
        Public Property RolloverPct() As System.Nullable(Of Decimal)
            Get
                Return Me.rolloverPctField
            End Get
            Set
                Me.rolloverPctField = value
                Me.RaisePropertyChanged("RolloverPct")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=7)>  _
        Public Property PayCommissionCode() As System.Nullable(Of Char)
            Get
                Return Me.payCommissionCodeField
            End Get
            Set
                Me.payCommissionCodeField = value
                Me.RaisePropertyChanged("PayCommissionCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=8)>  _
        Public Property EffDate() As System.Nullable(Of Date)
            Get
                Return Me.effDateField
            End Get
            Set
                Me.effDateField = value
                Me.RaisePropertyChanged("EffDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=9)>  _
        Public Property ExpDate() As System.Nullable(Of Date)
            Get
                Return Me.expDateField
            End Get
            Set
                Me.expDateField = value
                Me.RaisePropertyChanged("ExpDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property [Date]() As Date
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
                Me.RaisePropertyChanged("Date")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property EnteredBy() As String
            Get
                Return Me.enteredByField
            End Get
            Set
                Me.enteredByField = value
                Me.RaisePropertyChanged("EnteredBy")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property AppliesToCode() As String
            Get
                Return Me.appliesToCodeField
            End Get
            Set
                Me.appliesToCodeField = value
                Me.RaisePropertyChanged("AppliesToCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property pgmProgram() As pgmProgram
            Get
                Return Me.pgmProgramField
            End Get
            Set
                Me.pgmProgramField = value
                Me.RaisePropertyChanged("pgmProgram")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class IVAN
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private iVANSField As String
        
        Private aMSField As String
        
        Private yAccountField As String
        
        Private isActiveField As Boolean
        
        Private userIDField As String
        
        Private dateField As Date
        
        Private enteredByField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property IVANS() As String
            Get
                Return Me.iVANSField
            End Get
            Set
                Me.iVANSField = value
                Me.RaisePropertyChanged("IVANS")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property AMS() As String
            Get
                Return Me.aMSField
            End Get
            Set
                Me.aMSField = value
                Me.RaisePropertyChanged("AMS")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property YAccount() As String
            Get
                Return Me.yAccountField
            End Get
            Set
                Me.yAccountField = value
                Me.RaisePropertyChanged("YAccount")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property isActive() As Boolean
            Get
                Return Me.isActiveField
            End Get
            Set
                Me.isActiveField = value
                Me.RaisePropertyChanged("isActive")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property UserID() As String
            Get
                Return Me.userIDField
            End Get
            Set
                Me.userIDField = value
                Me.RaisePropertyChanged("UserID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property [Date]() As Date
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
                Me.RaisePropertyChanged("Date")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property EnteredBy() As String
            Get
                Return Me.enteredByField
            End Get
            Set
                Me.enteredByField = value
                Me.RaisePropertyChanged("EnteredBy")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class LocationIVAN
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private locationIDField As Decimal
        
        Private iVANSField As String
        
        Private dateField As Date
        
        Private enteredByField As String
        
        Private iVANField As IVAN
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property LocationID() As Decimal
            Get
                Return Me.locationIDField
            End Get
            Set
                Me.locationIDField = value
                Me.RaisePropertyChanged("LocationID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property IVANS() As String
            Get
                Return Me.iVANSField
            End Get
            Set
                Me.iVANSField = value
                Me.RaisePropertyChanged("IVANS")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property [Date]() As Date
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
                Me.RaisePropertyChanged("Date")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property EnteredBy() As String
            Get
                Return Me.enteredByField
            End Get
            Set
                Me.enteredByField = value
                Me.RaisePropertyChanged("EnteredBy")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property IVAN() As IVAN
            Get
                Return Me.iVANField
            End Get
            Set
                Me.iVANField = value
                Me.RaisePropertyChanged("IVAN")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class Bank
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private bankIdField As Decimal
        
        Private accountNameField As String
        
        Private bankNameField As String
        
        Private accountNumberField As String
        
        Private routingNumberField As String
        
        Private accountTypeCodeField As String
        
        Private isActiveField As Boolean
        
        Private bankAccountTypeField As String
        
        Private dateField As Date
        
        Private enteredByField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property BankId() As Decimal
            Get
                Return Me.bankIdField
            End Get
            Set
                Me.bankIdField = value
                Me.RaisePropertyChanged("BankId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property AccountName() As String
            Get
                Return Me.accountNameField
            End Get
            Set
                Me.accountNameField = value
                Me.RaisePropertyChanged("AccountName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property BankName() As String
            Get
                Return Me.bankNameField
            End Get
            Set
                Me.bankNameField = value
                Me.RaisePropertyChanged("BankName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property AccountNumber() As String
            Get
                Return Me.accountNumberField
            End Get
            Set
                Me.accountNumberField = value
                Me.RaisePropertyChanged("AccountNumber")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property RoutingNumber() As String
            Get
                Return Me.routingNumberField
            End Get
            Set
                Me.routingNumberField = value
                Me.RaisePropertyChanged("RoutingNumber")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property AccountTypeCode() As String
            Get
                Return Me.accountTypeCodeField
            End Get
            Set
                Me.accountTypeCodeField = value
                Me.RaisePropertyChanged("AccountTypeCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property isActive() As Boolean
            Get
                Return Me.isActiveField
            End Get
            Set
                Me.isActiveField = value
                Me.RaisePropertyChanged("isActive")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property BankAccountType() As String
            Get
                Return Me.bankAccountTypeField
            End Get
            Set
                Me.bankAccountTypeField = value
                Me.RaisePropertyChanged("BankAccountType")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property [Date]() As Date
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
                Me.RaisePropertyChanged("Date")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property EnteredBy() As String
            Get
                Return Me.enteredByField
            End Get
            Set
                Me.enteredByField = value
                Me.RaisePropertyChanged("EnteredBy")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="com.insurcloud")>  _
    Partial Public Class LocationBank
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private locationIdField As Decimal
        
        Private bankIdField As Decimal
        
        Private accountTypeCodeField As String
        
        Private dateField As Date
        
        Private enteredByField As String
        
        Private bankField As Bank
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property LocationId() As Decimal
            Get
                Return Me.locationIdField
            End Get
            Set
                Me.locationIdField = value
                Me.RaisePropertyChanged("LocationId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property BankId() As Decimal
            Get
                Return Me.bankIdField
            End Get
            Set
                Me.bankIdField = value
                Me.RaisePropertyChanged("BankId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property AccountTypeCode() As String
            Get
                Return Me.accountTypeCodeField
            End Get
            Set
                Me.accountTypeCodeField = value
                Me.RaisePropertyChanged("AccountTypeCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property [Date]() As Date
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
                Me.RaisePropertyChanged("Date")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property EnteredBy() As String
            Get
                Return Me.enteredByField
            End Get
            Set
                Me.enteredByField = value
                Me.RaisePropertyChanged("EnteredBy")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property Bank() As Bank
            Get
                Return Me.bankField
            End Get
            Set
                Me.bankField = value
                Me.RaisePropertyChanged("Bank")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface InsurCloudAMSServiceSoapChannel
        Inherits MarketingCRMService.InsurCloudAMSServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class InsurCloudAMSServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of MarketingCRMService.InsurCloudAMSServiceSoap)
        Implements MarketingCRMService.InsurCloudAMSServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function InsertAgency(ByRef oAgency As MarketingCRMService.Agency, ByVal isPASAgency As Boolean) As String Implements MarketingCRMService.InsurCloudAMSServiceSoap.InsertAgency
            Return MyBase.Channel.InsertAgency(oAgency, isPASAgency)
        End Function
        
        Public Function InsertLocation(ByRef oLoc As MarketingCRMService.Location, ByRef oAgent As MarketingCRMService.Agency, ByVal isPASAgency As Boolean) As String Implements MarketingCRMService.InsurCloudAMSServiceSoap.InsertLocation
            Return MyBase.Channel.InsertLocation(oLoc, oAgent, isPASAgency)
        End Function
        
        Public Function InsertBank(ByVal oObject As Object, ByRef oBank As MarketingCRMService.Bank) As String Implements MarketingCRMService.InsurCloudAMSServiceSoap.InsertBank
            Return MyBase.Channel.InsertBank(oObject, oBank)
        End Function
        
        Public Function GetActivePrograms(ByVal productCode As Integer, ByVal stateCode As String) As MarketingCRMService.Program() Implements MarketingCRMService.InsurCloudAMSServiceSoap.GetActivePrograms
            Return MyBase.Channel.GetActivePrograms(productCode, stateCode)
        End Function
        
        Public Function InsertProgram(ByRef oProg As MarketingCRMService.LocationProgram, ByVal ProgramCode As String) As String Implements MarketingCRMService.InsurCloudAMSServiceSoap.InsertProgram
            Return MyBase.Channel.InsertProgram(oProg, ProgramCode)
        End Function
        
        Public Function LoadAgency(ByVal AgentCode As String, ByVal LoadAll As Boolean, ByVal ProgramCode As String) As MarketingCRMService.Agency Implements MarketingCRMService.InsurCloudAMSServiceSoap.LoadAgency
            Return MyBase.Channel.LoadAgency(AgentCode, LoadAll, ProgramCode)
        End Function
        
        Public Function GetOptions(ByVal AgentCode As String) As System.Data.DataSet Implements MarketingCRMService.InsurCloudAMSServiceSoap.GetOptions
            Return MyBase.Channel.GetOptions(AgentCode)
        End Function
        
        Public Function isInSameGroup(ByVal AgentCode1 As String, ByVal AgentCode2 As String) As String Implements MarketingCRMService.InsurCloudAMSServiceSoap.isInSameGroup
            Return MyBase.Channel.isInSameGroup(AgentCode1, AgentCode2)
        End Function
        
        Public Function IsCommissionStatementPaperless(ByVal agencyId As String) As Boolean Implements MarketingCRMService.InsurCloudAMSServiceSoap.IsCommissionStatementPaperless
            Return MyBase.Channel.IsCommissionStatementPaperless(agencyId)
        End Function
        
        Public Function CommissionStatementPaperlessUpdate(ByVal agencyId As String, ByVal isPaperless As Boolean) As Boolean Implements MarketingCRMService.InsurCloudAMSServiceSoap.CommissionStatementPaperlessUpdate
            Return MyBase.Channel.CommissionStatementPaperlessUpdate(agencyId, isPaperless)
        End Function
        
        Public Function CommissionLoginIsAllowed(ByVal LocationCode As String) As Boolean Implements MarketingCRMService.InsurCloudAMSServiceSoap.CommissionLoginIsAllowed
            Return MyBase.Channel.CommissionLoginIsAllowed(LocationCode)
        End Function
        
        Public Function CommissionLoginCreate(ByVal LocationCode As String, ByVal Password As String, ByVal CreatedBy As String) As Boolean Implements MarketingCRMService.InsurCloudAMSServiceSoap.CommissionLoginCreate
            Return MyBase.Channel.CommissionLoginCreate(LocationCode, Password, CreatedBy)
        End Function
        
        Public Function CommissionLoginUpdate(ByVal LocationCode As String, ByVal NewPassword As String, ByVal UpdatedPasswordBy As String) As Boolean Implements MarketingCRMService.InsurCloudAMSServiceSoap.CommissionLoginUpdate
            Return MyBase.Channel.CommissionLoginUpdate(LocationCode, NewPassword, UpdatedPasswordBy)
        End Function
        
        Public Function CommissionLoginUpdateForAgent(ByVal LocationCode As String, ByVal OldPassword As String, ByVal NewPassword As String, ByVal UpdatedPasswordBy As String) As Boolean Implements MarketingCRMService.InsurCloudAMSServiceSoap.CommissionLoginUpdateForAgent
            Return MyBase.Channel.CommissionLoginUpdateForAgent(LocationCode, OldPassword, NewPassword, UpdatedPasswordBy)
        End Function
        
        Public Function CommissionLoginIsRegistered(ByVal LocationCode As String) As Boolean Implements MarketingCRMService.InsurCloudAMSServiceSoap.CommissionLoginIsRegistered
            Return MyBase.Channel.CommissionLoginIsRegistered(LocationCode)
        End Function
        
        Public Function CommissionLoginIsRegisteredInfoValid(ByVal LocationCode As String, ByVal TaxIDorSSN As String, ByVal ZipCode As String) As Boolean Implements MarketingCRMService.InsurCloudAMSServiceSoap.CommissionLoginIsRegisteredInfoValid
            Return MyBase.Channel.CommissionLoginIsRegisteredInfoValid(LocationCode, TaxIDorSSN, ZipCode)
        End Function
        
        Public Function CommissionLogin(ByVal LocationCode As String, ByVal Password As String) As Boolean Implements MarketingCRMService.InsurCloudAMSServiceSoap.CommissionLogin
            Return MyBase.Channel.CommissionLogin(LocationCode, Password)
        End Function
        
        Public Function CommissionLoginEmailUpdate(ByVal LocationCode As String, ByVal NewEmail As String) As Boolean Implements MarketingCRMService.InsurCloudAMSServiceSoap.CommissionLoginEmailUpdate
            Return MyBase.Channel.CommissionLoginEmailUpdate(LocationCode, NewEmail)
        End Function
        
        Public Function ESignatureStatusUpdate(ByVal agencyId As String, ByVal isESignature As Boolean) As Boolean Implements MarketingCRMService.InsurCloudAMSServiceSoap.ESignatureStatusUpdate
            Return MyBase.Channel.ESignatureStatusUpdate(agencyId, isESignature)
        End Function
        
        Public Function ResetAgentPassword(ByVal agent As MarketingCRMService.BaseAgent) As Boolean Implements MarketingCRMService.InsurCloudAMSServiceSoap.ResetAgentPassword
            Return MyBase.Channel.ResetAgentPassword(agent)
        End Function
        
        Public Function UpdateAgentPassword(ByVal agent As MarketingCRMService.BaseAgent) As Boolean Implements MarketingCRMService.InsurCloudAMSServiceSoap.UpdateAgentPassword
            Return MyBase.Channel.UpdateAgentPassword(agent)
        End Function
        
        Public Function IsAgentRequiredToUpdatePassword(ByVal agent As MarketingCRMService.BaseAgent) As Boolean Implements MarketingCRMService.InsurCloudAMSServiceSoap.IsAgentRequiredToUpdatePassword
            Return MyBase.Channel.IsAgentRequiredToUpdatePassword(agent)
        End Function
        
        Public Function LoadMarketingComboBox(ByVal sProgramType As String, ByVal sCategory As String, ByVal sSubCategory As String, ByVal sAppliesToCode As String, ByVal dtRateDate As Date) As System.Data.DataSet Implements MarketingCRMService.InsurCloudAMSServiceSoap.LoadMarketingComboBox
            Return MyBase.Channel.LoadMarketingComboBox(sProgramType, sCategory, sSubCategory, sAppliesToCode, dtRateDate)
        End Function
    End Class
End Namespace
